<?php
/**
 * @file
 * Main section for the Resave Nodes module.
 *
 * This module will resave nodes of selected content types based on various
 * rules (created/updated since last time cron was run, or just all nodes
 * regardless of create/update time) at configured times (via cron).
 * This will force computed fields to be computed
 * (geolocation, media players, etc.).
 */

require_once backdrop_get_path('module', 'resave_nodes') . '/inc/resave_nodes.form_admin.inc';
require_once backdrop_get_path('module', 'resave_nodes') . '/inc/resave_nodes.func_general.inc';

/**
 * Implements hook_menu().
 */
function resave_nodes_menu() {
  $items['admin/config/system/resave_nodes'] = array(
    'title' => 'Resave Nodes',
    'description' => t('Configure the content types and frequency for resaving nodes.'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('resave_nodes_form'),
    'access arguments' => array('administer node resaving'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function resave_nodes_permission() {
  return array(
    'administer node resaving' => array(
      'title' => t('Administer the content types and frequency for resaving nodes.'),
    ),
  );
}

/**
 * Implements hook_config_info().
 */
function resave_nodes_config_info() {
  $prefixes['resave_nodes.settings'] = array(
    'label' => t('Resave Nodes settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_cron().
 */
function resave_nodes_cron() {
  $resave_nodes_scheduling = config_get('resave_nodes.settings', 'use_cron');

  if ($resave_nodes_scheduling == 'run_with_cron') {
    resave_nodes_do_that_thing();
  }
}
